### ISSUE TITLE
Can't launch steam image

### ISSUE THREAD

**Issue by SpaccaGoblin24** [tianon/dockerfiles#112]
I tried to run the steam docker image with this command: `docker run -it --rm --device /dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix:ro --ipc host -e DISPLAY tianon/steam bash`, but i can't open steam after the installation because i got this error:
 ```
Loaded SDL version 2.0.13-6142881
sh: 1: lspci: not found
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Steam: An X Error occurred
X Error of failed request:  GLXBadContext
Major opcode of failed request:  151
Serial number of failed request:  46
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  151
Value in failed request:  0x0
Serial number of failed request:  45
xerror_handler: X failed, continuing
Steam: An X Error occurred
X Error of failed request:  BadMatch (invalid parameter attributes)
Major opcode of failed request:  151
Serial number of failed request:  47
```
I am using artixlinux with runit and a nvidia card with proprietary drivers

**Comment by tianon** [comment]
Unfortunately, to run GL-needing containers on an nVidia system using the proprietary driver requires getting the correct version of the GL libraries inside your container as well.

What I use for my nVidia system at home is https://github.com/tianon/docker-bin/blob/master/nvidiize (which will take an arbitrary image and attempt to run nVidia's installer inside it).

**Comment by SpaccaGoblin24** [comment]
I got error  `./nvidiize: line 58: $1: unbound variable`

**Comment by tianon** [comment]
Try `./nvidiize tianon/steam`

**Comment by SpaccaGoblin24** [comment]
`Error: No such image: tianon/steam`

**Comment by tianon** [comment]
`docker pull tianon/steam` ? (is this not on the same node where you already tried to run the image?)

**Comment by SpaccaGoblin24** [comment]
I forgot that I ran `docker system prune -a` before i opened this issue

**Comment by SpaccaGoblin24** [comment]
now i get this error `The command '/bin/sh -c set -eux;       wget -O /tmp/nvidia.run "http://us.download.nvidia.com/XFree86/Linux-x86_64/$NVIDIA_VERSION/NVIDIA-Linux-x86_64-$NVIDIA_VERSION.run" --progress=dot:giga;       chmod +x /tmp/nvidia.run' returned a non-zero code: 8`

**Comment by SpaccaGoblin24** [comment]
```
steam@af2515d409df:/$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...

(zenity:294): dbind-WARNING **: 19:00:41.182: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-qHcDzFPqME: Connection refused
Can't find 'steam-runtime-check-requirements', continuing anyway
/home/steam/.local/share/Steam/ubuntu12_32/steam
[2020-12-04 19:00:44] Startup - updater built Oct 28 2020 23:34:22
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Installing breakpad exception handler for appid(steam)/version(0)
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```
Now i got this error, i ran the container with this command `docker run -it --rm --device /dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix:ro --ipc host -e DISPLAY tianon/steam:nvidia-455.45.01 bash`

**Comment by tianon** [comment]
You'll also need the nVidia kernel bits in the container - I usually just include all `/dev/nvidia*` devices (which on my machine includes `/dev/nvidia0`, `/dev/nvidiactl`, and `/dev/nvidia-modeset`) -- one `--device` flag for each.

**Comment by SpaccaGoblin24** [comment]
it's working, thanks
