### ISSUE TITLE
exim4 docker image 

### ISSUE THREAD

**Issue by csetepeter** [tianon/dockerfiles#116]
Hey, I'm getting the following error while using your docker image. I've talked to a couple people using the image and they're all getting the same error. Is there anything we can do? Our setup was working before your last change.

Connecting to aspmx.l.google.com [172.217.218.27]:25 ... failed: Connection timed out (timeout=5m)
mail_1        |   273 LOG: MAIN
mail_1        |   273   H=aspmx.l.google.com [172.217.218.27] Connection timed out
mail_1        |   273 Connecting to alt1.aspmx.l.google.com [2a00:1450:4010:c03::1b]:25 ... failed: Cannot assign requested address
mail_1        |   273 LOG: MAIN
mail_1        |   273   H=alt1.aspmx.l.google.com [2a00:1450:4010:c03::1b] Cannot assign requested address
mail_1        |   273 Connecting to alt2.aspmx.l.google.com [2404:6800:4003:c06::1b]:25 ... failed: Cannot assign requested address
mail_1        |   273 LOG: MAIN
mail_1        |   273   H=alt2.aspmx.l.google.com [2404:6800:4003:c06::1b] Cannot assign requested address
mail_1        |   273 Connecting to alt1.aspmx.l.google.com [209.85.233.26]:25 ... failed: Connection timed out (timeout=5m)
mail_1        |   273 LOG: MAIN
mail_1        |   273   H=alt1.aspmx.l.google.com [209.85.233.26] Connection timed out
mail_1        |   273 Connecting to aspmx3.googlemail.com [2404:6800:4003:c06::1a]:25 ... failed: Cannot assign requested address
mail_1        |   273 LOG: MAIN
mail_1        |   273   H=aspmx3.googlemail.com [2404:6800:4003:c06::1a] Cannot assign requested address
mail_1        |   272 LOG: MAIN
mail_1        |   272   == (my email) R=dnslookup T=remote_smtp defer (99): Cannot assign requested address

**Comment by tianon** [comment]
Hmm, that's odd -- can you elaborate what you mean by "your last change" ?  The last time I changed the image in any functional way was in November of last year (ab9aaee1147ae153df449a3b7c3f4bd663b22e88), and it definitely wasn't substantial.  The last "meaty" change to the actual build was in May of last year (58fe414db3ce38355fe641941ed2f2c557584fb4).

The version of `exim4` we install comes from Debian, but the version number on that is `4.92-8+deb10u4`, which is from last May as well:

```
exim4 (4.92-8+deb10u4) buster-security; urgency=high

...

 -- Andreas Metzler <ametzler@debian.org>  Wed, 13 May 2020 18:01:31 +0200
```

So I'm guessing it's more likely that Google's changed something here (or you're experiencing a shared environmental issue). :confused:

**Comment by tianon** [comment]
I also have an instance of this that I run locally (sending email through Google), and I just made sure it was on my very latest pushed image and sent a test email through it successfully. :confused:

**Comment by csetepeter** [comment]
Ah, it might've been something with google, not quite sure what though, we've been using the image for around a year now and just noticed that it broke for us somehow. I'll try to debug the issue and get back to you with it.
