### ISSUE TITLE
Steam container runs DotA, but no sound

### ISSUE THREAD

**Issue by aurium** [tianon/dockerfiles#119]
I try this:
`docker run -e DISPLAY=${DISPLAY} -v /dev/dri:/dev/dri -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm -v /run/user/${UID}/pulse:/run/user/${UID}/pulse -v /etc/machine-id:/etc/machine-id -v ${HOME}/Downloads:/tmp/Downloads --privileged=true --device /dev/snd -v $HOME/.steam:/home/steam/.steam -v $HOME/.local/share/Steam:/home/steam/.local/share/Steam tianon/steam`

It installs and runs Steam and from its interface is possible to install and run DotA. The video settings works, but audio settings shows no output option.

**Comment by tianon** [comment]
Whoa, you definitely want to ditch `--privileged=true`.

I'm not sure exactly what's going wrong here, but I imagine you might need more environment variables to let Steam know where to look for PulseAudio.

It's a bit complex, but https://github.com/tianon/docker-bin/blob/master/homes-docker is how I currently run Steam in a container.

**Comment by aurium** [comment]
Hi @tianon,

I read your `homes-docker`, and it looks like a interesting approach to securely run applications on a GNU/Linux machine. Am I right?

Is this a part of a bigger project?

Why your list of supported software are hardcoded inside the script? I believe we could read config files from a directory, and that means dynamically fill the `case` block. What you think?

**Comment by tianon** [comment]
It's hard coded because it's implemented as symlinks to the script :sweat_smile: (and I haven't had a chance to refactor it to something else just yet) -- what I've (re-)discovered is that I've essentially reimplemented https://subuser.org/ though, and poorly at that, so I'd really probably suggest using that instead.

**Comment by aurium** [comment]
Oh! Great! I'll read that.
