### ISSUE TITLE
About docker in docker - how to make it work without parent sock file

### ISSUE THREAD

**Issue by aviNrich** [tianon/dockerfiles#129]
Hi,
I have tried your docker in docker solution from here: https://github.com/docker-library/docker/issues/306#issuecomment-815338333
In my docker compose file, if I wont add the following volume I will get an error:
`  - /var/run/docker.sock:/var/run/docker.sock`
The error...
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

How can I run the Docker file without bein dependent on the host docker engine? 

If its not possible, how can I connect to my dockers via localhost. `mysql -u root -h localhost -p ` not working, 

Thanks

**Comment by tianon** [comment]
I think maybe you should back up a hitch and describe what you're trying to accomplish?
