### ISSUE TITLE
syncthing having trouble auto-upgrading

### ISSUE THREAD

**Issue by soichih** [tianon/dockerfiles#13]
I am seeing following error message generated from the syncthing container.

```
21:35:36: Automatic upgrade: open /usr/local/bin/syncthing621167713: permission denied
```

I think this is expected, because syncthing is running under "user" user. Is there any problem with running as root inside the container?

**Comment by exetico** [comment]
Did you find a solution? I'm in the same situation right now.

**Comment by tianon** [comment]
Yeah, this is expected -- I usually destroy and recreate my container to
upgrade syncthing, same as all my other containers. :+1: (Especially since
any upgrade wouldn't be persistent otherwise.)

**Comment by soichih** [comment]
Is there any side effect if you run syncthing as root?

**Comment by tianon** [comment]
Hmm, interesting question -- probably won't be any side effect, but might
be dangerous depending on what you bind-mount into the container (and will
probably break permissions on your files by making them all "root:root" as
it syncs them).

**Comment by tianon** [comment]
`tianon/syncthing` is now provided by https://github.com/tianon/docker-syncthing -- if this issue still applies, I'd recommend filing an issue over there so we can discuss further! :+1:
