### ISSUE TITLE
tianon/steam troubles to initiate steam

### ISSUE THREAD

**Issue by x11tete11x** [tianon/dockerfiles#16]
Hi! thx for your awesome work, im getting this when i want start steam:

STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)

and after "accept licence" screen, Steam just hangs there, any clue of what happens? :D

**Comment by tianon** [comment]
I just tried the same and I get the "Updating Steam..." dialog which then
downloads the steam platform appropriately, extracts it, and then prompts
me to login. :confused:
