### ISSUE TITLE
syncthing-cli in syncthing

### ISSUE THREAD

**Issue by johnjelinek** [tianon/dockerfiles#19]
I'm using syncthing to sync data containers in my docker swarm cluster. Kind of like this: https://labs.ctl.io/persistent-distributed-filesystems-in-docker-without-nfs-or-gluster/. It would be great if you could include the syncthing-cli in the base syncthing image. Since I'm not mounting configs on the host, it's hard to use the syncthing-cli container to config the syncthing container because it starts out hosting on `127.0.0.1` instead of `0.0.0.0`.

**Comment by tianon** [comment]
Hmm, interesting point -- do you think a combination of `--volumes-from some-syncthing-container` and `--net container:some-syncthing-container` might be a way to solve this too? (if your configs already do or could live in a volume)

**Comment by johnjelinek** [comment]
well, so far I haven't needed to use --net container:some-syncthing-container. --volumes-from seems to be sufficient :)

**Comment by johnjelinek** [comment]
it sure is painful setting up each of the containers at the beginning. Lots of `docker exec` and adding devices/folders via the cli

**Comment by tianon** [comment]
Yeah, I can imagine!  That's why I bind-mount, but even then it's a PITA to
set up a new host. :disappointed:

**Comment by johnjelinek** [comment]
hrmm ... after sharing all the default folders it seems there is some conflict with the folder IDs. oy, maybe I should try configuring it via the URL -- I didn't really want to mount a volume w/ a config that opened it to `0.0.0.0` to build the configs so I could add the nodes. This is tricky.

**Comment by johnjelinek** [comment]
guess I'll go the btsync route for now.

**Comment by johnjelinek** [comment]
btw https://github.com/syncthing/syncthing/releases/tag/v0.12.6

**Comment by johnjelinek** [comment]
I haven't given up on syncthing yet ... found a source of inspiration: https://github.com/withinboredom/docker-blue-volume.

Would it be ok to add the user to sudoers? I want to sync folders like `/usr/local/etc/haproxy`. So I'll need to create that directory, methinks

**Comment by johnjelinek** [comment]
hrmm ... I ended up rebuilding the repo without adding `USER` so it would have root access to the volume mount. I'm not sure of another way to manage the permissions between all my swarm nodes.

**Comment by tianon** [comment]
You should be able to just run with "-u root" -- I usually run as my own
UID explicitly, actually

**Comment by johnjelinek** [comment]
Cool, I completely forgot about that



—

**Comment by tianon** [comment]
`tianon/syncthing` is now provided by https://github.com/tianon/docker-syncthing -- if this issue still applies, I'd recommend filing an issue over there so we can discuss further! :+1:
