### ISSUE TITLE
misleading docker hub documentation about /etc/mailname

### ISSUE THREAD

**Issue by morrizon** [tianon/dockerfiles#197]
In [docker hub](https://hub.docker.com/r/tianon/exim4) we can see the following doc:

> You probably want to bind-mount in some kind of /etc/mailname that actually makes sense. Probably also worth setting -h to the same value. Something like -v /etc/mailname:/etc/mailname:ro -h "$(cat /etc/mailname)" might be reasonable.

The doc was a little misleading for me because I understood that I could modify `/etc/mailname` without changing the hostname but it was not true.  It looks like inside the container `/etc/mailname` is a soft link pointing to `/etc/hostname` so if you only mount `/etc/mailname` the content will modify the linked `/etc/hostname` to be modified again when running the container by the assigned hostname (random or specified via the `-h` option). Finally, `/etc/mailname` will have always the content of the defined hostname. Basically, to modify the mailname we only need modify the hostname. If we want different names, a new image should be created without that soft link.

Maybe a new doc like the following makes more sense:

> You probably want to change /etc/mailname in something that actually makes sense. That file is soft linked to /etc/hostname so changing the hostname will  be enough. Something like -h "$(cat /etc/mailname)" might be reasonable. If you want a different hostname , a new image without the soft link should be created.

**Comment by tianon** [comment]
Oops, yes, that was updated in https://github.com/tianon/dockerfiles/commit/2da87b48edc80e48f4809074078cf5efd8f96574 but I never adjusted the documentation to match -- just supplying `--hostname` to the container should be sufficient now. :+1:
