### ISSUE TITLE
syncthing: tags

### ISSUE THREAD

**Issue by johnjelinek** [tianon/dockerfiles#20]
Can you please make tags for syncthing versions?

**Comment by johnjelinek** [comment]
now's a good time. syncthing 0.12.8 is out now.

**Comment by tianon** [comment]
Yeah, sorry for not posting here -- I've made tags now (and they come from
https://github.com/tianon/docker-syncthing instead).  I asked Docker
whether they could move my automated builds over to that other repo, but
they said I can't unless I delete and recreate, which is pretty
disappointing, so for now I'm just building locally and pushing myself.  I
need to update the README with more info, but the image is indeed updated
for 0.12.8 (https://hub.docker.com/r/tianon/syncthing/tags/). :+1:

**Comment by tianon** [comment]
Thanks for the prod to actually do all this! :heart:

**Comment by tianon** [comment]
This one's fixed! :smile:
