### ISSUE TITLE
No audio in steam

### ISSUE THREAD

**Issue by JuanCrg90** [tianon/dockerfiles#25]
Hi, i'm trying the steam docker in a arch linux machine, but i can't listen the audio in the games.

i'm using the next line to start the container.

```
$ sudo docker run --name=steam -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/shm:/dev/shm -v /run/user/${UID}/pulse:/run/user/${UID}/pulse -v /etc/machine-id:/etc/machine-id -v ${HOME}/Downloads:/tmp/Downloads -e DISPLAY=${DISPLAY} tianon/steam
```

exist any form to fix this?

Regards.

**Comment by tianon** [comment]
I've personally never had great success with "sound" in containers, so I'm likely the wrong person to ask. :disappointed:

**Comment by natostanco** [comment]
https://github.com/jfrazelle/dockerfiles/issues/85#issuecomment-210903811

**Comment by tehbmar** [comment]
I'm not super experienced with docker bu I have used a container a while back that support audio in spotify.

https://hub.docker.com/r/jess/spotify/~/dockerfile/

Basically for that image it came down to installing alsa-utils and passing the sound device with --device /dev/snd:/dev/snd

I tried install alsa-utils in the image but packages are missing and I'm not familiar with steamOS, but with this new info it might be a quick fix?

**Comment by PureTryOut** [comment]
I got PulseAudio working in the container by setting the environment variable `PULSE_SERVER` to `unix:/run/user/$UID/pulse/native`. This way it uses the PulseAudio server of your host instead of trying to use one in the container (which obviously fails).

**Comment by SuperSandro2000** [comment]
Adding ``--device /dev/snd -e ALSA_CARD=PCH`` to my docker run command did the trick for me.

You can find the name of your sound card with ``aplay -l``. The name is shown after ``card X:``.

**Comment by tianon** [comment]
Yep, sounds like this has two reasonable solutions based on whether your host is fully ALSA or using PulseAudio. :+1:

**Comment by rdlmda** [comment]
I managed to fix my issue with alsa by (1) getting pulseaudio to work, and then (2) getting alsa to use pulseaudio by default, by placing this on the container's home folder (save as `~/.asoundrc):

```
# Default to PulseAudio

pcm.!default {
    type pulse
    hint {
        show on
        description "Default ALSA Output (currently PulseAudio Sound Server)"
    }
}

ctl.!default {
    type pulse
}
```
