### ISSUE TITLE
Consider more LTS version of tianon/ubuntu-devel

### ISSUE THREAD

**Issue by dol** [tianon/dockerfiles#27]
I really like the tianon/ubuntu-devel image. It's very useful to have a simple 'build farm'. But currently the image is based of Xenial.
It would be nice to have images for all the LTS versions like Precise (12.04) and Trusty (14.04).

**Comment by tianon** [comment]
It was actually a bug that this was still based on Xenial -- I've updated it to Yakkety, but sometime next week we should have an `ubuntu:devel` tag available that will auto-move based on the most recent "development" release of Ubuntu.

**Comment by dol** [comment]
Ok, now I understand the intension of the image. I used the image to build packages for different LTS version, which is quite handy.

**Comment by tianon** [comment]
Ah yeah, this image is targeted more towards development tools than strictly building tools.  For that, you probably want to just take whichever base image you're interested in and install `build-essential` and/or `devscripts` to build your packages more directly. :+1:
