### ISSUE TITLE
Xen Orcherstra 5.1 just released

### ISSUE THREAD

**Issue by kalbasit** [tianon/dockerfiles#29]
[Xen Orchestra 5.1](https://xen-orchestra.com/blog/xen-orchestra-5-1/) was just released, can you please update your docker image?

**Comment by tianon** [comment]
Oh man, I am really sorry I didn't see this when I made https://github.com/tianon/dockerfiles/commit/471075cdf7dcdcd2cd2ca4007096f5ef74d393e3 and https://github.com/tianon/dockerfiles/commit/ce9ec67b7728293c90211095c85d39fceb2fac9e. :disappointed:

It's updated now, thanks! :+1: :heart:
