### ISSUE TITLE
Set a fixed IP to the container

### ISSUE THREAD

**Issue by dashohoxha** [tianon/dockerfiles#3]
I have created a script like this
```bash
#!/bin/bash
ip addr flush dev eth0
ip addr add 172.17.0.10/16 dev eth0
ip ro add to default via 172.17.42.1 dev eth0
```
I call this script from `/etc/rc.local` but I find out that the IP has not been set. When I call it from command line it works. Any idea on what is going on or how to set a fixed IP?

**Comment by tianon** [comment]
Now that `docker run` has a `--ip` flag, I think we can safely close this. :smile:
