### ISSUE TITLE
can't locate the signal-desktop

### ISSUE THREAD

**Issue by charleshugo** [tianon/dockerfiles#307]
When I 
`docker build -t signal-desktop .`
I encounter

E: Unable to locate package signal-desktop
------
executor failed running [/bin/sh -c set -eux;   apt-get update;        apt-get install -y --no-install-recommends            signal-desktop="$SIGNAL_DESKTOP_VERSION"                 libatk-bridge2.0-0             libatk1.0-0             libdrm2       libgbm1          libgtk-3-0              libx11-xcb1           libxshmfence1    ;       rm -rf /var/lib/apt/lists/*;    signal="$(command -v signal-desktop)";         signal="$(readlink -ev "$signal")";    ! { ldd "$signal" | grep 'not found'; }]: exit code: 100

**Comment by charleshugo** [comment]
I encounter this issue on Macbook Air M1, but didn't encounter this issue on Linux.

**Comment by tianon** [comment]
Ah, that's the missing piece!  This package probably isn't published
by the Signal project for arm64 (https://signal.org/download/).
