### ISSUE TITLE
Joystick on steam

### ISSUE THREAD

**Issue by mdkcore0** [tianon/dockerfiles#33]
Hey guys, I almost have all I need working with the steam dockerfile. But... anyone had luck (or tried) to get joystick running inside docker?

I have some xbox 360 controllers, they all are working on the host (slackware x86_64) with steamos-xpad, But can't make it work inside docker.

I am running it with privileged access. Also, I can do a cat on /dev/input/js0 inside docker and see something happening there (the same if I do it on slackware).

Thanks for the awesome dockerfile!

**Comment by tianon** [comment]
If you can figure out which device node Steam or the game you're interested in is trying to access, you can use `--device` to give the container access without running the full container as privileged.  For determining that, `strace` might be a helpful tool, but I'll warn you that it's output is going to be very, very verbose. :smile:

**Comment by rodrigogolive** [comment]
Hey @tianon, thanks for your help!

I played a little with some docker flags and managed to get my joysticks working inside your dockerfile. A mix of bind mount of _/dev/input_ with privileged.

For instance, I ran Super Meat Boy and Fez with a wireless Xbox 360 controller. No problem with input, but every time I press the start button on SMB, the sound stops. No problem with FEZ, though. This is strange, but will test with other games and try to remove unneeded flags to run this and see what happens.

Thanks again!

**Comment by tianon** [comment]
Whew, massive delay here -- discussed in https://github.com/tianon/dockerfiles/issues/60#issuecomment-631145541, I did some revamping of my image and tested today and found `--device /dev/input` was plenty for my `xpad`-supported Xbox 360 controller. :+1:

No `--privileged` necessary! :metal:
