### ISSUE TITLE
tianon/true image is not using true-asm

### ISSUE THREAD

**Issue by Sirtea** [tianon/dockerfiles#39]
Hello,

I use tianon/true image a lot.
Last time I pulled the image, his weight was 125 bytes, as the true-asm binary on your git repo, and also same weight when I compile true.asm with nasm on debian:jessie.
Today, I realize that the images wights 146 bytes, that's more than expected, and makes me thing that true-asm is not the latest.

Please fix

**Comment by tianon** [comment]
Huh, that's odd -- it's definitely built with the right binary: https://github.com/tianon/dockerfiles/blob/149a552051ffdbc150fcd690846cc076690611c9/true/Dockerfile#L2 (`ADD true-asm /true`)

The binary itself is also the expected size: https://github.com/tianon/dockerfiles/blob/149a552051ffdbc150fcd690846cc076690611c9/true/true-asm (`125 bytes`)

All I can figure is that maybe Docker's showing some of the metadata size in the listing now?

Regardless, a few bytes won't make much functional difference -- it's still smaller than a single packet, but more importantly, the minimum size for an entry in a tar file is still _much_ larger than this, which is how the registry transmits these.

**Comment by tianon** [comment]
I'm not sure what the root cause was, but I updated `ADD` to be `COPY` instead, and the rebuilt image appears to be the expected 125 bytes now. :+1:
