### ISSUE TITLE
Enable TRIM in Qemu

### ISSUE THREAD

**Issue by egandro** [tianon/dockerfiles#40]
Hello,

I found an interessting way to autoshrink the COW files of QEmu.

https://blog.zencoffee.org/2016/05/trim-support-kvm-virtual-machines/

You may add a switch set the disk to SCSI with TRIM enabled.

Thank you and great Work!

**Comment by tianon** [comment]
If you look at the line where I set up `QEMU_HDA` arguments for QEMU, you'll see that I already include `discard=unmap`: (https://github.com/tianon/dockerfiles/blob/d083f6929a44595cb17f7bdbd3a6418aaf4a24f0/qemu/start-qemu#L50)

```bash
	qemuArgs+=( -drive file="$QEMU_HDA",index=0,media=disk,discard=unmap )
```
:+1: :smile:

(Added with an embarassingly descriptive commit message in https://github.com/tianon/dockerfiles/commit/72bb59768e03f179a9000401dc260d752354e17e :innocent:)
