### ISSUE TITLE
LaTeX: update Debian to stretch

### ISSUE THREAD

**Issue by rubdos** [tianon/dockerfiles#47]
Stretch is the current stable distribution, released 2017-06-17. It would be nice to have the newer LaTeX packages too.

Afaik, it would be as simple as changing debian:jessie to debian:stretch in the relevant Dockerfile.

You can also have a `tianon/latex:jessie` tag to point to the "old" Debian 8, for those who still need it.

Currently testing whether that statement is true. I'll report back in a min :-)

**Comment by tianon** [comment]
Thanks, good call!  I also switched to the `-slim` variant of Debian which helped us save ~1GB from the final image size!

**Comment by rubdos** [comment]
Woah, you closed this faster that I could build the image! [Mine is here](https://hub.docker.com/r/rubdos/latex), but I guess I don't need it anymore now :'-)

Thanks!

**Comment by tianon** [comment]
Hahaha, yeah, it's a really heavy build. 😇👍
