### ISSUE TITLE
Not able to run the steam container

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tianon/dockerfiles#50]
My sh file
#!/bin/bash
sudo docker run --name=$1 -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/nvidia0:/dev/nvidia0 -v /dev/nvidiactl:/dev/nvidiactl -v /dev/nvidia-uvm:/dev/nvidia-uvm -v /dev/shm:/dev/shm -v /run/user/${UID}/pulse:/run/user/${UID}/pulse -v /etc/machine-id:/etc/machine-id -v ${HOME}/Downloads:/tmp/Downloads -e DISPLAY=${DISPLAY} tianon/steam
------------------------------------------------------------------------------------------------------------------
Console Output
./run.sh                                                                         
Setting up Steam content in /home/steam/.local/share/Steam
/home/steam/.local/share/Steam/steam.sh: line 99: no match: **:
Running Steam on steamos 2.0 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
-----------------------------------------------------------------------------------------------------------------------
The container doesnot to exit or do anything

**Comment by tianon** [comment]
Sorry for the delay.  Getting OpenGL actually _working_ inside a container is often tricky.  In my experience, using Intel integrated graphics is the _easiest_ solution, but for others you have to essentially match not only drivers, but even explicit driver versions inside and outside the containers.  Sorry!

**Comment by Jesse-Millwood** [comment]
@tianon what docker run command do you use for the steam and/or lutris containers?

**Comment by tianon** [comment]
@Jesse-Millwood great question!  I didn't have it when I last commented on this issue, but I've since rewritten my Steam/Lutris/X+GL wrapper at https://github.com/tianon/docker-bin/blob/master/steam-docker and should probably link it from several image descriptions :sweat_smile:
