### ISSUE TITLE
Could you share the dockerfile you use to build the image "tianon/centos:6.5"?

### ISSUE THREAD

**Issue by kenliang18** [tianon/dockerfiles#53]
Hi Tianon!Could you share the dockerfile you use to build the image "tianon/centos:6.5"?I just want to know the difference between the official one and yours.Thanks a lot.

**Comment by tianon** [comment]
It was probably created via https://github.com/moby/moby/blob/6ba1e91877691c4043b57c97090668bc4fd874b6/contrib/mkimage/rinse -- I'd really recommend against using it, especially since the official one is generated and maintained directly by the CentOS release engineering team.
