### ISSUE TITLE
https://hub.docker.com/r/tianon/docker-master/ contains dead links

### ISSUE THREAD

**Issue by AkihiroSuda** [tianon/dockerfiles#54]
https://hub.docker.com/r/tianon/docker-master/ contains dead links.

https://github.com/tianon/dockerfiles/tree/master/docker needs to be substituted with https://github.com/tianon/dockerfiles/tree/master/docker-master

@tianon

**Comment by tianon** [comment]
Fixed thanks

**Comment by AkihiroSuda** [comment]
thanks but still one deadlink is left

>  See https://github.com/tianon/dockerfiles/tree/master/docker for the relevant source for these images.
