### ISSUE TITLE
qemu 3.1

### ISSUE THREAD

**Issue by StefanSchoof** [tianon/dockerfiles#58]
There is a [qemu 3.1.0 release](https://www.qemu.org/2018/12/12/qemu-3-1-0/). Have you any plans to update the qemu image?

**Comment by tianon** [comment]
This is something I'm interested in, although I now use this image in enough places that I'm a little wary of updating it without some proper testing.  Perhaps it's finally time to split `tianon/qemu` out from https://github.com/tianon/dockerfiles like I've done with https://github.com/tianon/docker-syncthing so I could more easily maintain multiple versions and update each consumer of it individually. :sweat_smile:

It looks like upstream supports at least 4 different version tracks simultaneously: https://www.qemu.org/download/#source (currently 3.1.0, 3.0.0, 2.12.1, 2.11.2), so it'd be cool to be able to publish for all of those IMO.
