### ISSUE TITLE
Add Python3 to Steam for Proton

### ISSUE THREAD

**Issue by PureTryOut** [tianon/dockerfiles#60]
The relatively new Steam Play feature of Steam, which uses Proton, requires Python 3 to be installed. However, the Steam container doesn't include this. Please include Python 3 so Windows games can be played via the Docker container.

**Comment by tianon** [comment]
Sorry for the delay. :sweat_smile:

This is a great suggestion -- I really wish Steam had some kind of official tool for checking whether our environment has what's necessary for properly running Steam. :disappointed:

I'm also increasingly getting the sense that Valve doesn't intend to support SteamOS in a sustainable way, so I'm thinking it might make sense to rebase this image back to Debian or possibly even Ubuntu (maybe there's some official documentation we could point to that recommends a particular environment for Linux users?)

**Comment by tianon** [comment]
Further evidence we need a change -- the current image installs `steam-installer` within SteamOS.  When I instead do something `FROM ubuntu:20.04` and install http://media.steampowered.com/client/installer/steam.deb (as documented on https://github.com/ValveSoftware/steam-for-linux#getting-started), it pulls in `python3` appropriately... :facepalm:

**Comment by SuperSandro2000** [comment]
Maybe the proton [Vagrant](https://github.com/ValveSoftware/Proton/blob/proton_5.0/Vagrantfile) file can help with that. 

Or we could take a look at [SteamOS](https://store.steampowered.com/steamos/buildyourown) what other interesting stuff it pulls in.

**Comment by tianon** [comment]
Updated to Ubuntu 20.04 in https://github.com/tianon/dockerfiles/commit/e53d5dc65fa7de2f7ddfc456f49a67eefdcb5709 -- I've successfully tested several Linux native games, but I haven't had any luck getting anything Proton-related to do anything but hang or crash (although granted, I don't actually own any of the officially whitelisted games, so I'm testing with the settings checkbox to allow any Windows game and using ProtonDB to determine whether the games I'm testing should *probably* work :sweat_smile:).

**Comment by SuperSandro2000** [comment]
So it crashed for right in the beginning about missing libcurl libraries.

```
Setting up Steam content in /home/steam/.local/share/Steam                                                                                                                                                        
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins potentially out-of-date, rebuilding...
Installing breakpad exception handler for appid(steam)/version(0)
[2020-05-20 18:36:24] Startup - updater built Apr  9 2019 22:48:20
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
../steamexe/updateui_xwin.cpp (339) : Assertion Failed: Could not open connection to X
sh: 1: /home/steam/.local/share/Steam/steam_msg.sh: not found
Installing breakpad exception handler for appid(steam)/version(1.0)
crash_20200520183624_3.dmp[2235]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200520183624_3.dmp
../steamexe/updateui_xwin.cpp (339) : Assertion Failed: Could not open connection to X
../steamexe/main.cpp (754) : Assertion Failed: failed to initialize update status ui, or create initial window
crash_20200520183624_3.dmp[2235]: Uploading dump (out-of-process)
/tmp/dumps/crash_20200520183624_3.dmp

../steamexe/main.cpp (754) : Assertion Failed: failed to initialize update status ui, or create initial window
crash_20200520183624_3.dmp[2235]: Finished uploading minidump (out-of-process): success = no
crash_20200520183624_3.dmp[2235]: Finished uploading minidump (out-of-process): success = no

crash_20200520183624_3.dmp[2235]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20200520183624_3.dmp[2235]: error: libcurl.so: cannot open shared object file: No such file or directory

crash_20200520183624_3.dmp[2235]: file ''/tmp/dumps/crash_20200520183624_3.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

crash_20200520183624_3.dmp[2235]: file ''/tmp/dumps/crash_20200520183624_3.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''

```

**Comment by tianon** [comment]
I think those `libcurl` errors are misdirecting -- it looks to me you didn't give the container access to an X server ("`../steamexe/updateui_xwin.cpp (339) : Assertion Failed: Could not open connection to X`"), and the `libcurl` errors are from it trying to upload the resulting crash dump back to Valve (which is also strange, but shouldn't be a big problem since it should work fine after it pulls down the Steam Runtime, but it uses `zenity`/X11 to report progress while it does so).

I've reordered the installation steps a bit in 048cc30 (moving `USER` down, moving other things further up like creating the user).

**Comment by SuperSandro2000** [comment]
Yeah you where right. Later I got a log message that it preferred to load its downloaded libraries. I think it would be a good idea to add a short help how to launch the image and how to get X server up and running correctly.

I am currently using ``docker run -e DISPLAY --network host --shm-size 4GB steam``. ``--shm-size`` is necessary or otherwise my library won't load. I did not test less than 4 GB work but I think it is a good value.

**Comment by tianon** [comment]
I've updated https://hub.docker.com/r/tianon/steam to link to https://github.com/tianon/docker-bin/blob/master/steam-docker which is what I'm currently using to test/run this -- it handles quite a few edge cases, but I haven't tested it on my system with an NVIDIA GPU yet, where I imagine I'll have to get more creative (possibly doing something with https://github.com/NVIDIA/nvidia-docker). :sweat_smile:

**Comment by tianon** [comment]
Ok, spent some more time on this, got NVIDIA working (via adjustments to my `steam-docker` launcher to install the correct version of the NVIDIA drivers to match my host), and successfully played "Insaniquarium! Deluxe" via Proton 5.0-7. :+1:
