### ISSUE TITLE
exim4 google smtp password

### ISSUE THREAD

**Issue by LuisLlana** [tianon/dockerfiles#68]
I have been using this docker for several months. I have not had any problem until last Monday. 
The server google gave me an authorisation error. 
I have had to change the file passwd.client in /etc/exim4 to include the gmail.com domain, as follows

*.gmail.com:XXXX@XXXXX:XXXXX

**Comment by jon-nfc** [comment]
I can confirm this error. initialy the /etc/exim4 was `*.google.com:XXXX@XXXXX:XXXXX` then when i changed it to  `*.gmail.com:XXXX@XXXXX:XXXXX` I no longer received the authentication error.

docker image used: `tianon/exim4:latest`, repo digest `tianon/exim4@sha256:47576911e22af8bee77870cbbe1756e328b72e6092f61795d08bc0f9881bbe08`

**Comment by arpagon** [comment]
Apparently google switched the smtp host to "smtp.gmail.com". Before october 16 it was a "*.google.com" host. I fixed the problem by configuring exim4 to use a username/password also for "smtp.gmail.com" in /etc/exim4/passwd.client

https://github.com/tianon/dockerfiles/pull/69
https://support.google.com/mail/thread/16940173?hl=en

**Comment by tianon** [comment]
Fixed by https://github.com/tianon/dockerfiles/pull/70.

**Comment by Mo-Xiyad** [comment]
I have been getting this error, does anyone have an idea to fix this issue?

Request Method: | POST
-- | --
http://localhost:8000/password-reset/
3.1.5
SMTPSenderRefused
(530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError c127sm2116210lfd.292 - gsmtp', 'webmaster@localhost')
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py, line 871, in sendmail
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
3.9.0
