### ISSUE TITLE
Handbrake

### ISSUE THREAD

**Issue by ChristoffBo** [tianon/dockerfiles#802]
Hi, sorry i would like to try your Handbrake container, but i dont see a docker compose?

Just need to volumes and ports please. apologies if it is in there and i cant seem to find it.

kind regards

**Comment by tianon** [comment]
Unfortunately, there's not a "standard" set of mounts I could suggest -- it all depends on your use case.

If you're only going to run `HandBrakeCLI`, then you'll only need to worry about volumes/mounts for config, sources, destinations, etc.

If you want to run the UI, you'll want to look into something like https://subuser.org/ to get your container connected to X11.

Regardless, running Handbrake inside a container is a bit of an advanced topic (in the interest of full disclosure), so I'll wish you good luck!
