### ISSUE TITLE
request for containerd 1.7.24

### ISSUE THREAD

**Issue by ddl-kfrench** [tianon/dockerfiles#859]
hey 👋  -- thank you for maintaining these images, wanted to check to see whether you intend to support the latest `1.7.x` `containerd` version released last week https://github.com/containerd/containerd/releases/tag/v1.7.24?

**Comment by tianon** [comment]
:smile: I have no memory of writing this line:

https://github.com/tianon/dockerfiles/blob/114b2efa0362a303c7cbd39cddebd126456c7ce3/containerd/versions.sh#L14

Yes, this is reasonable :+1:

Out of curiosity, I'd love to know what you're using the images for, if you don't mind sharing? :eyes:

**Comment by ddl-kfrench** [comment]
thanks so much! wanted to run sanity checks that the latest 1.7.x patch works with some snapshotter plugins and yours is the only repo with any recent updates. really appreciate it!
