### ISSUE TITLE
skype: Failed to move to new namespace

### ISSUE THREAD

**Issue by bremner** [tianon/dockerfiles#86]
I was trying
```
$ docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix:ro -e DISPLAY="unix$DISPLAY" tianon/skype
```
But I get 
```
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
```
I see some advice that I should 
```
 sudo sysctl 'kernel.unprivileged_userns_clone=1'
```

And other advice that I should never ever do that. In either case, doing it does not seem to change things. 

I'm grateful for any advice / suggestions. I'm a docker newb. This is on debian testing, with the debian kernel 5.5.0-1

**Comment by tianon** [comment]
Ouch, this one's hairy.  I played a little bit and couldn't find a satisfactory general solution, but I can reproduce the issue.

I don't actually use the Skype client (and only updated it because it's here and I've got a script to help automate updates), so really I should probably deprecate the image instead (which unfortunately doesn't really help you, sorry!)

**Comment by bremner** [comment]
Tianon Gravi <notifications@github.com> writes:

> Ouch, this one's hairy.  I played a little bit and couldn't find a
> satisfactory general solution, but I can reproduce the issue.
>
> I don't actually use the Skype client (and only updated it because
> it's here and I've got a script to help automate updates), so really I
> should probably deprecate the image instead (which unfortunately
> doesn't really help you, sorry!)
>

No worries, you don't owe me anything ;).

I ended up using the official (I think) flatpak for skype.

d

**Comment by tianon** [comment]
That's probably a good plan; flatpak is generally better suited for this sort of usage (it's designed for it, really). 😅

Thanks for understanding ❤️
