### ISSUE TITLE
ehour image does not work

### ISSUE THREAD

**Issue by laurentlabat** [tianon/dockerfiles#87]
Hello, 
I tried to use the ehour docker image following the instalation guide provided here : 
https://github.com/tianon/dockerfiles/tree/master/ehour

We end with the following error message:
Error 404 - Not Found.
No context on this server matched or handled this request.
Contexts known to this server are:

Looking at the logs, I an find the following:
04-23@07:41:05 INFO  org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet

Can we get that fixed ? 

thanks,

**Comment by tianon** [comment]
I went to verify and copy-pasted the instructions from that REAMDE verbatim and everything worked fine here. :confused:

**Comment by tianon** [comment]
Closing -- without a reproducer, there's not anything I can do. :disappointed:
