### ISSUE TITLE
sed: can't read .muttrc: No such file or directory

### ISSUE THREAD

**Issue by hub20xx** [tianon/dockerfiles#93]
Hi, 

first of all, sorry as it may well not be an issue... 

I can't get mutt-gmail to work.

After a lot of googling and tweaking, still no success / progress.

So I guess I'd ask here.

Here is what I have and what I did:
My setup:
- linux ubuntu with docker, compose, both working normally
- my linux host / machine username `hostusername`
- my gmail account username `gmailaccountuser`

Here is what I did:

- `mkdir -p ~/docker-mutt/gmailaccountuser` (ie. `/home/hostusername/docker-mutt/gmailaccountuser`)
- `cd ~/docker-mutt/`
- `touch start-gmailaccountuser && chmod +x ./start-gmailaccountuser` to launch mutt-gmail with my `gmailaccountuser` with this script
- the script `start-gmailaccountuser` contains this:
```
#!/bin/sh

docker run -it --rm \
    -e TERM \
    -e GMAIL=gmailaccountuser@gmail.com \
    -e GMAIL_NAME='gmailaccount user' \
    -u "$(id -u):$(id -g)" \
    -e HOME=/home/hostusername/docker-mutt/gmailaccountuser \
    -v "$HOME/.signature:/home/user/.signature" \
    -v "$HOME/.muttrc:/home/user/.muttrc.local" \
    -v "$HOME/.mutt/cache:/home/user/.mutt/cache" \
    tianon/mutt-gmail
```

When I'm in `~/docker-mutt/` and I run the script `./start-gmailaccountuser`, I get `sed: can't read /home/hostusername/docker-mutt/gmailaccountuser/.muttrc: No such file or directory`.

I did `touch /home/hostusername/docker-mutt/gmailaccountuser/.muttrc`, rerun the script, stillt the same error.
When I run the command saved in the script directly in my terminal, I get the same error.
When I change the permissions to 644 or 755 for .muttrc, I get the same error.

Any idea how to fix it?

Any help / suggestion would be appreciated!

Thanks in advance

**Comment by tianon** [comment]
I think the problem is that you're setting the container's `HOME` environment variable to `/home/hostusername/docker-mutt/gmailaccountuser` (which is the path on your host), but that path doesn't exist inside the container.  I think you want to set that to `/home/user` instead.

**Comment by hub20xx** [comment]
Thank you @tianon ! I modified the command so now it is like this:
```
docker run -it --rm \
    -e TERM \
    -e GMAIL=gmailaccountuser@gmail.com \
    -e GMAIL_NAME='gmailaccount user' \
    -u "$(id -u):$(id -g)" \
    -e HOME=/home/user \
    -v "$HOME/.signature:/home/user/.signature" \
    -v "$HOME/.muttrc:/home/user/.muttrc.local" \
    -v "$HOME/.mutt/cache:/home/user/.mutt/cache" \
    tianon/mutt-gmail
```
but then I get the following error:
```
sed: couldn't open temporary file /home/user/sed8FOvTf: Permission denied
```
Shouldn't `-e HOME=/home/user` be a path on the host, so that the volumes set by 
```
    -v "$HOME/.signature:/home/user/.signature" \
    -v "$HOME/.muttrc:/home/user/.muttrc.local" \
    -v "$HOME/.mutt/cache:/home/user/.mutt/cache" \
```
are set correctly?

**Comment by tianon** [comment]
Ah, it probably only works on my machine because `user` inside the container is uid 1000:1000 and matches the user on my host. :confused:

I guess the image needs to be updated to make `/home/user` have wider permissions. :disappointed:

If you don't care which UID/GID the image actually runs as, you could try this:

```console
$ docker run -it --rm \
    -e TERM \
    -e GMAIL=gmailaccountuser@gmail.com \
    -e GMAIL_NAME='gmailaccount user' \
    -v "$HOME/.signature:/home/user/.signature:ro" \
    -v "$HOME/.muttrc:/home/user/.muttrc.local:ro" \
    -v "mutt-gmailaccountuser:/home/user/.mutt/cache" \
    tianon/mutt-gmail
```

(The important bit there is using a named volume for `~/.mutt/cache` instead of a host volume.)

If you don't care about the local cache (which isn't necessary, but makes repeated runs *significantly* faster), you can even ditch that volume completely.

**Comment by hub20xx** [comment]
Thank you a lot for helping with this!

I used the command you mentioned but I still get `sed: couldn't open temporary file /home/user/sedeQk8dH: Permission denied`.

**Comment by tianon** [comment]
Ok, let's try simplifying even further to try and narrow this down -- does the following work?  (I just tested and it successfully prompts me for a password)

```console
$ docker run -it --rm \
    -e TERM \
    -e GMAIL=gmailaccountuser@gmail.com \
    -e GMAIL_NAME='gmailaccount user' \
    tianon/mutt-gmail
```

**Comment by hub20xx** [comment]
No, it doesn't, I get `sed: couldn't open temporary file /home/user/sedKEMqZU: Permission denied`

**Comment by tianon** [comment]
I can't reproduce :confused: 

https://asciinema.org/a/bY2vBS5KAHWIP2kfGFQyoYQnt
